server:
  port: 8189
spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/otus?currentSchema=reactive
    username: otus
    password: otus
  flyway:
    url: jdbc:postgresql://postgres:5432/otus?currentSchema=reactive
    user: otus
    password: otus
    driver-class-name: org.postgresql.Driver